import 'package:flutter/material.dart';
import 'package:inno_store/assets.dart';

final List<Map<String, String>> allProducts = [
  {
    "title": "Swisse Ultiboost Vitamin C + Manuka Honey 120 Tablets",
    "image": Assets.vitaminc,
    "category": "Health Care",
    "price": "RM 79.99",
  },
  {
    "title": "Swisse Ultiboost High Strength Krill Oil 30 Capsules",
    "image": Assets.krilloil,
    "category": "Health Care",
    "price": "RM 59.99",
  },
  {
    "title": "Blackmores Digestive Enzymes Plus Capsule 60s",
    "image": Assets.enzymesplus,
    "category": "Health Care",
    "price": "RM 89.99",
  },
  {
    "title": "Blackmores Bio Ace Plus Capsule 30s",
    "image": Assets.bioaceplus,
    "category": "Health Care",
    "price": "RM 99.99",
  },
  {
    "title": "Blackmores Bio Zinc Capsule 168s",
    "image": Assets.biozinc,
    "category": "Health Care",
    "price": "RM 69.99",
  },
  {
    "title": "Blackmores Buffered C Capsule 30s",
    "image": Assets.bufferedc,
    "category": "Health Care",
    "price": "RM 39.99",
  },
  {
    "title": "EYS Bird's Nest With Rock Sugar",
    "image": Assets.birdnest,
    "category": "Health Care",
    "price": "RM 129.99",
  },
  {
    "title": "EYS Pure Chicken Essence",
    "image": Assets.chickenessence,
    "category": "Health Care",
    "price": "RM 109.99",
  },
  {
    "title": "HM Euphoria Longana Honey",
    "image": Assets.honey,
    "category": "Health Care",
    "price": "RM 49.99",
  },
  {
    "title": "Brand's Essence of Chicken 70g x 30's",
    "image": Assets.brands,
    "category": "Health Care",
    "price": "RM 159.99",
  },
  {
    "title": "Nestle Koko Krunch 450g",
    "image": Assets.kokokrunch,
    "category": "Groceries",
    "price": "RM 12.99",
  },
  {
    "title": "Saji Brand Cooking Oil 5kg",
    "image": Assets.saji,
    "category": "Groceries",
    "price": "RM 29.99",
  },
  {
    "title": "Knife Cooking Oil 5kg",
    "image": Assets.knifeoil,
    "category": "Groceries",
    "price": "RM 24.99",
  },
  {
    "title": "Maggi Curry Flavour Instant Noodles 79g x 5",
    "image": Assets.maggiekari,
    "category": "Groceries",
    "price": "RM 4.99",
  },
  {
    "title": "Old Town 2 in 1 White Coffee (Coffee & Creamer) 375g",
    "image": Assets.oldtown,
    "category": "Groceries",
    "price": "RM 13.99",
  },
  {
    "title": "Old Town 3-in-1 Hazelnut Instant White Coffee 570g",
    "image": Assets.oldtownhazelnut,
    "category": "Groceries",
    "price": "RM 15.99",
  },
  {
    "title": "Yeo's Chicken Curry with Potatoes 280g",
    "image": Assets.yeoscurry,
    "category": "Groceries",
    "price": "RM 7.99",
  },
  {
    "title": "Jasmine Super 5 White Rice Imported 5kg",
    "image": Assets.jasmine,
    "category": "Groceries",
    "price": "RM 18.99",
  },
  {
    "title": "Ayam Brand Mackerel in Tomato Sauce 230g",
    "image": Assets.tomatosauce,
    "category": "Groceries",
    "price": "RM 7.99",
  },
  {
    "title": "Cap Rambutan 5% Super Import White Rice 5kg",
    "image": Assets.rambutans,
    "category": "Groceries",
    "price": "RM 17.99",
  },
  {
    "title": "Milo Original Chocolate Malt Drink 30g x 18",
    "image": Assets.milo,
    "category": "Groceries",
    "price": "RM 16.99",
  },
  {
    "title": "Nestle Kit Kat Sharebag Value Pack 17g x 24",
    "image": Assets.kitkat,
    "category": "Groceries",
    "price": "RM 19.99",
  },
  {
    "title": "Milo Soft Pack 2kg",
    "image": Assets.milo2kg,
    "category": "Groceries",
    "price": "RM 27.99",
  },
  {
    "title": "Garnier Skin Naturals Micellar Water Pink 125ml",
    "image": Assets.garnier,
    "category": "Make Up",
    "price": "RM 10.99",
  },
  {
    "title": "Reihaku Hatomugi Whip Face Wash Cleansing Water (Make Up Remover) 200ml",
    "image": Assets.hatomugi,
    "category": "Make Up",
    "price": "RM 14.99",
  },
  {
    "title": "Garnier Micellar Salicylic BHA 125ml",
    "image": Assets.garnierblue,
    "category": "Make Up",
    "price": "RM 12.99",
  },
  {
    "title": "Silky White Bright Up Liquid Foundation 01 Light",
    "image": Assets.foundation,
    "category": "Make Up",
    "price": "RM 18.99",
  },
  {
    "title": "Palladio Herbal Foundation Tube PFS01 Ivory",
    "image": Assets.palladio,
    "category": "Make Up",
    "price": "RM 22.99",
  },
  {
    "title": "Palladio Herbal Foundation Tube PFS02 Porcelain",
    "image": Assets.palladio02,
    "category": "Make Up",
    "price": "RM 22.99",
  },
  {
    "title": "Palladio Dual Wet & Dry Foundation WD400 Laurel Nude",
    "image": Assets.dryfoundation,
    "category": "Make Up",
    "price": "RM 24.99",
  },
  {
    "title": "Palladio Dual Wet & Dry Foundation WD401 Ivory Myrrh",
    "image": Assets.dryfoundation401,
    "category": "Make Up",
    "price": "RM 24.99",
  },
  {
    "title": "Rimmel Wonder'Ink Ultimate Waterproof Eyeliner",
    "image": Assets.eyeliner,
    "category": "Make Up",
    "price": "RM 19.99",
  },
  {
    "title": "SilkyGirl Long-Wearing Eyeliner 01 Black Black",
    "image": Assets.eyelinerblack,
    "category": "Make Up",
    "price": "RM 12.99",
  },
  {
    "title": "Dog Dry Food Chicken & Veg 3kg",
    "image": Assets.pedigree,
    "category": "Pets Care",
    "price": "RM 39.99",
  },
  {
    "title": "Cat Wet Food Flake Tuna in Gravy 85gm",
    "image": Assets.sheba,
    "category": "Pets Care",
    "price": "RM 4.99",
  },
  {
    "title": "Dog Oral Care Dentastix Toy 60g",
    "image": Assets.dogoral,
    "category": "Pets Care",
    "price": "RM 9.99",
  },
  {
    "title": "Potty Here Training Aid Spray 8Oz",
    "image": Assets.naturvet,
    "category": "Pets Care",
    "price": "RM 14.99",
  },
  {
    "title": "Ear Wash Liquid 4Oz",
    "image": Assets.earwash,
    "category": "Pets Care",
    "price": "RM 11.99",
  },
  {
    "title": "Peony Anti-Bacteria Formula Pets Shampoo 400ml",
    "image": Assets.shampoo,
    "category": "Pets Care",
    "price": "RM 19.99",
  },
  {
    "title": "Unique Pet Shower Silicon Brush with Soap Container",
    "image": Assets.brush,
    "category": "Pets Care",
    "price": "RM 24.99",
  },
  {
    "title": "KUNDAL Honey & Macadamia Nature Shampoo - Cherry Blossom 500ml",
    "image": Assets.kundalshampoo,
    "category": "Hair Care",
    "price": "RM 29.99",
  },
  {
    "title": "Kundal Honey & Macadamia Hair Treatment - Cherry Blossom 500ml",
    "image": Assets.kundalhoney,
    "category": "Hair Care",
    "price": "RM 34.99",
  },
  {
    "title": "Grafen Perfume Hair Shampoo Emerald Blossom 500ml (Anti-Hair Loss)",
    "image": Assets.grafen,
    "category": "Hair Care",
    "price": "RM 39.99",
  },
  {
    "title": "Ryo Hair Loss Expert Scalp Massage Essence 80ml",
    "image": Assets.ryo,
    "category": "Hair Care",
    "price": "RM 44.99",
  },
  {
    "title": "Kundal Caffeine Scalp Care Tonic 100ml",
    "image": Assets.hairtonic,
    "category": "Hair Care",
    "price": "RM 49.99",
  },
  {
    "title": "Pantene 3Mm Conditioner 480Ml Keratin Silky Smooth",
    "image": Assets.pantene,
    "category": "Hair Care",
    "price": "RM 19.99",
  },
  {
    "title": "Amino Mason Treatment Night Recipe Sleek 450Ml",
    "image": Assets.amino,
    "category": "Hair Care",
    "price": "RM 29.99",
  },
  {
    "title": "Ryo Damage Care And Nourishing Shampoo 480ml",
    "image": Assets.ryodamage,
    "category": "Hair Care",
    "price": "RM 34.99",
  },
];
