name: inno_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: any
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.5
  carousel_slider: ^4.2.1
  flutter_blue_plus: ^1.16.2
  get: ^4.6.5
  permission_handler: ^11.3.1
  collection: ^1.18.0
  geolocator: ^12.0.0
  rxdart: ^0.28.0
  firebase_database: ^10.5.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/point.png
    - assets/40%.jpg
    - assets/20%.jpg
    - assets/member.jpg
    - assets/map/floorplan.jpg
    
    - assets/products/groceries/kokokrunch.jpg
    - assets/products/groceries/saji.jpg
    - assets/products/groceries/knifeoil.jpg
    - assets/products/groceries/maggiekari.jpg
    - assets/products/groceries/yeoscurry.jpg
    - assets/products/groceries/jasmine.jpg
    - assets/products/groceries/tomatosauce.jpg
    - assets/products/groceries/rambutan.jpg
    - assets/products/groceries/kitkat.jpg
    
    - assets/products/dairy_product/milo2kg.jpg
    - assets/products/dairy_product/milo.jpg
    - assets/products/dairy_product/milk.jpg

    - assets/products/coffee/oldtown.jpg
    - assets/products/coffee/oldtownhazelnut.jpg

    - assets/products/supplements/vitaminc.jpg
    - assets/products/supplements/krilloil.png
    - assets/products/supplements/enzymesplus.jpg
    - assets/products/supplements/bioaceplus.jpg
    - assets/products/supplements/biozinc.jpg
    - assets/products/supplements/bufferedc.jpg

    - assets/products/tonic/chickenessence.jpg
    - assets/products/tonic/brands.jpg

    - assets/products/nutrition/birdnest.jpg
    - assets/products/nutrition/honey.jpg

    - assets/products/foot_treament/freeman.jpg
    - assets/products/foot_treament/ellgy.jpg
    - assets/products/foot_treament/lotion.jpg

    - assets/products/traditional_medicine/kangaroo.jpg
    - assets/products/traditional_medicine/kapak.jpg
    - assets/products/traditional_medicine/kwan.jpg
    - assets/products/traditional_medicine/yuyee.jpg

    - assets/products/makeup/garnier.jpg
    - assets/products/makeup/hatomugi.jpg
    - assets/products/makeup/garnierblue.jpg
    - assets/products/makeup/foundation.jpg
    - assets/products/makeup/palladio.jpg
    - assets/products/makeup/palladio02.jpg
    - assets/products/makeup/dryfoundation.jpg
    - assets/products/makeup/dryfoundation401.jpg
    - assets/products/makeup/eyeliner.jpg
    - assets/products/makeup/eyelinerblack.jpg

    - assets/products/petcare/pedigree.jpg
    - assets/products/petcare/sheba.jpg
    - assets/products/petcare/dogoral.jpg
    - assets/products/petcare/whiskas.jpg
    - assets/products/petcare/naturvet.jpg
    - assets/products/petcare/earwash.jpg
    - assets/products/petcare/shampoo.jpg
    - assets/products/petcare/brush.jpg
    - assets/products/petcare/pet.jpg

    - assets/products/haircare/kundalshampoo.jpg
    - assets/products/haircare/kundalhoney.jpg
    - assets/products/haircare/grafen.jpg
    - assets/products/haircare/ryo.jpg
    - assets/products/haircare/hairtonic.jpg
    - assets/products/haircare/pantene.jpg
    - assets/products/haircare/amino.jpg
    - assets/products/haircare/ryodamage.jpg

    - assets/cashier/boost.png
    - assets/cashier/grabpay.png
    - assets/cashier/touch_n_go.png
    - assets/cashier/visa.png
    - assets/cashier/mastercard.png


    
