name: inno_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: any
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.5
  carousel_slider: ^4.2.1
  flutter_blue_plus: ^1.16.2
  get: ^4.6.5
  permission_handler: ^11.3.1
  collection: ^1.18.0
  geolocator: ^12.0.0
  rxdart: ^0.28.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/products/healthcare/vitaminc.jpg
    - assets/products/healthcare/krilloil.png
    - assets/products/groceries/kokokrunch.jpg
    - assets/map/floorplan.jpg